### ISSUE TITLE
Segfault when erasing the only element

### ISSUE THREAD

**Issue by TotalKrill** [korken89/esl#1]
Program received signal SIGSEGV, Segmentation fault.
esl::static_vector<esl::function_view<void (long, unsigned long long, unsigned long long)>, 20u, esl::error_functions::noop>::erase(esl::function_view<void (long, unsigned long long, unsigned long long)>*, esl::function_view<void (long, unsigned long long, unsigned long long)>*) (
    end=0x20005940 <wf+1736>, begin=0x2001fff8, this=0x200049d0 <mac+16>)
    at lib/esl/src/esl/containers/static_vector.hpp:284
284	      *begin = *next;

**Comment by korken89** [comment]
There is a test for single element erase. Please provide more info or a minimal example that triggers the error. However, your `begin` and `end` pointer are vastly apart, did you call with a faulty argument?

You can enable the error handling, it will detect out of bounds access on the vector.
```C++
esl::static_vector< int, 20, esl::error_functions::halt > my_vec = /* ... */
```
